services:
  jtrial:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${BUILD_CONTEXT}/dNodeArch/docker/r2julia-file
      args:
        REL_SCRIBE_LOC: ${REL_SCRIBE_LOC}
        REL_DNODEJ_LOC: ${REL_DNODEJ_LOC}
    container_name: jtrial
    command: bash